#!/usr/bin/env python3
"""
Test the fixed control flow implementation
"""

import sys
import os

# Add the project root to the path
project_root = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, project_root)

from Petri.VMToPetri import VMToPetriTranslator

def test_basic_control_flow():
    """Test basic control flow operations"""
    print("Testing basic control flow operations...")
    
    # Test 1: Simple goto loop (the original failing case)
    print("\n1. Testing simple goto loop (loop_count=0, increment=1)")
    translator = VMToPetriTranslator()
    
    commands = [
        ("function", "test_func", 2),  # locals: counter, accumulator
        # Initialize counter and accumulator
        ("push", "constant", 0),
        ("pop", "local", 0),  # counter = 0
        ("push", "constant", 0),
        ("pop", "local", 1),  # accumulator = 0
        
        ("label", "LOOP_START"),
        # Check if counter < loop_count
        ("push", "local", 0),
        ("push", "constant", 0),  # loop_count = 0
        ("lt",),
        ("if-goto", "LOOP_BODY"),
        ("goto", "LOOP_END"),
        
        ("label", "LOOP_BODY"),
        # accumulator += increment
        ("push", "local", 1),
        ("push", "constant", 1),  # increment = 1
        ("add",),
        ("pop", "local", 1),
        # counter++
        ("push", "local", 0),
        ("push", "constant", 1),
        ("add",),
        ("pop", "local", 0),
        ("goto", "LOOP_START"),
        
        ("label", "LOOP_END"),
        # Return accumulator
        ("push", "local", 1),
        ("return",),
        ("call", "test_func", 0)
    ]
    
    result = translator.execute_program(commands)
    expected = 0  # loop_count * increment = 0 * 1 = 0
    
    if len(result) == 1 and result[0] == expected:
        print(f"✅ PASSED: expected={expected}, got={result[0]}")
    else:
        print(f"❌ FAILED: expected={expected}, got={result[0] if result else 'None'}")
        return False
    
    # Test 2: Simple if-goto
    print("\n2. Testing simple if-goto")
    translator = VMToPetriTranslator()
    
    commands = [
        ("function", "test_func", 0),
        ("push", "constant", 1),  # True condition
        ("if-goto", "TRUE_BRANCH"),
        # False branch
        ("push", "constant", 999),
        ("goto", "END"),
        ("label", "TRUE_BRANCH"),
        # True branch
        ("push", "constant", 42),
        ("label", "END"),
        ("return",),
        ("call", "test_func", 0)
    ]
    
    result = translator.execute_program(commands)
    expected = 42
    
    if len(result) == 1 and result[0] == expected:
        print(f"✅ PASSED: expected={expected}, got={result[0]}")
    else:
        print(f"❌ FAILED: expected={expected}, got={result[0] if result else 'None'}")
        return False
    
    # Test 3: Cross-scope jump (function to main program)
    print("\n3. Testing cross-scope jump")
    translator = VMToPetriTranslator()
    
    commands = [
        ("function", "test_func", 0),
        ("goto", "MAIN_LABEL"),
        # This should be skipped
        ("push", "constant", 999),
        ("return",),
        ("call", "test_func", 0),
        ("label", "MAIN_LABEL"),
        ("push", "constant", 123),
        ("return",)
    ]
    
    result = translator.execute_program(commands)
    expected = 123
    
    if len(result) == 1 and result[0] == expected:
        print(f"✅ PASSED: expected={expected}, got={result[0]}")
    else:
        print(f"❌ FAILED: expected={expected}, got={result[0] if result else 'None'}")
        return False
    
    return True

def test_property_based_samples():
    """Test a few specific cases that might be generated by property-based testing"""
    print("\nTesting property-based samples...")
    
    # Test cases that might be problematic
    test_cases = [
        # (loop_count, increment)
        (0, 1),   # Original failing case
        (1, 1),   # Simple case
        (2, 2),   # Medium case
        (3, 1),   # Larger loop
    ]
    
    for i, (loop_count, increment) in enumerate(test_cases):
        print(f"\n{i+1}. Testing goto loop: loop_count={loop_count}, increment={increment}")
        
        translator = VMToPetriTranslator()
        
        commands = [
            ("function", "test_func", 2),  # locals: counter, accumulator
            # Initialize counter and accumulator
            ("push", "constant", 0),
            ("pop", "local", 0),  # counter = 0
            ("push", "constant", 0),
            ("pop", "local", 1),  # accumulator = 0
            
            ("label", "LOOP_START"),
            # Check if counter < loop_count
            ("push", "local", 0),
            ("push", "constant", loop_count),
            ("lt",),
            ("if-goto", "LOOP_BODY"),
            ("goto", "LOOP_END"),
            
            ("label", "LOOP_BODY"),
            # accumulator += increment
            ("push", "local", 1),
            ("push", "constant", increment),
            ("add",),
            ("pop", "local", 1),
            # counter++
            ("push", "local", 0),
            ("push", "constant", 1),
            ("add",),
            ("pop", "local", 0),
            ("goto", "LOOP_START"),
            
            ("label", "LOOP_END"),
            # Return accumulator
            ("push", "local", 1),
            ("return",),
            ("call", "test_func", 0)
        ]
        
        result = translator.execute_program(commands)
        expected = loop_count * increment
        
        if len(result) == 1 and result[0] == expected:
            print(f"✅ PASSED: expected={expected}, got={result[0]}")
        else:
            print(f"❌ FAILED: expected={expected}, got={result[0] if result else 'None'}")
            return False
    
    return True

if __name__ == "__main__":
    print("Testing Fixed Control Flow Implementation")
    print("=" * 50)
    
    success = True
    
    if not test_basic_control_flow():
        success = False
    
    if not test_property_based_samples():
        success = False
    
    print("\n" + "=" * 50)
    if success:
        print("🎉 ALL TESTS PASSED!")
        print("The control flow implementation is working correctly.")
        print("The original issue has been fixed.")
    else:
        print("❌ SOME TESTS FAILED!")
        print("There are still issues with the control flow implementation.")